name: Build document
on: [ push, create ]
jobs:
  make-document:
    name: Compile document
    runs-on: ubuntu-latest
    container:
      image: k4zuki/pandocker-alpine:2.19-core
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup safe directory for git
        run: |
          repo=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}
          git config --global --add safe.directory /__w/${repo}/${repo}
      - name: Update dependencies
        run: |
          pip3 install pandocker-lua-filters docx-coreprop-writer #--break-system-packages 
          pip3 install git+https://github.com/k4zuki/pandoc_misc.git@2.16.2 #--break-system-packages
      - name: Prepare QR code for this build (at a tag)
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: |
          pip3 install qrcode
          make html
          RELEASE_VERSION=${GITHUB_REF#refs/*/}
          DOWNLOAD_URL_BASE=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download
          TARGET=`ls Out/*.html`
          TARGET=${TARGET#Out/}
          qr ${DOWNLOAD_URL_BASE}/${RELEASE_VERSION}/${TARGET//.html/}.pdf > images/QRcode.png
      - name: Build document
        run: |
          make docx
      - name: Make a release (at a tag)
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            docs/Out/*.docx
            docs/Out/*.html
      - name: Upload artifact files (at a push)
        uses: actions/upload-artifact@v3
        with:
          path: docs/Out

  windows:
    runs-on: windows-latest
    #    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    steps:
      - name: wait for artifact
        uses: yogeshlonkar/wait-for-jobs@v0
        with:
          jobs: "make-document"
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
        with:
          path: docs/Out/*.docx
      - name: Install Office
        run: choco install office365business # This takes about 5min
